import './globals.css'
import Navigation from '@/components/Navigation/Navigation'

export const metadata = {
  title: 'Mi Primer Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="container mx-auto">
          <Navigation/>
      {children}</body>
    </html>
  )
}
